export const colors = {
  primary: '#2563EB',
  primaryHover: '#1D4ED8',
  primaryLight: '#EFF6FF',
  primaryLightBorder: '#BFDBFE',
  dark: '#0F172A',
  body: '#64748B',
  muted: '#94A3B8',
  border: '#E2E8F0',
  white: '#FFFFFF',
  background: '#FFFFFF',
  surface: '#F5F7FA',
  success: '#10B981',
  successLight: '#ECFDF5',
  successBorder: '#A7F3D0',
  warning: '#F59E0B',
  warningLight: '#FFFBEB',
  warningBorder: '#FDE68A',
  purple: '#8B5CF6',
  purpleLight: '#F5F3FF',
  purpleBorder: '#DDD6FE',
};
