// mockDb.js — Persistent local database simulation using localStorage

const DEFAULT_ORDERS = [
  {
    id: "ORD-291",
    date: "16 Jun 2026, 10:30 AM",
    requiredDate: "18 Jun 2026",
    status: "New",
    paymentStatus: "Pending",
    deliveryStatus: "Pending",
    amount: "₹21,000",
    city: "Mumbai",
    owner: {
      name: "Rahul Mehta",
      business: "The Meridian Hotels",
      phone: "+91 98765 43210",
      email: "procurement@meridian.com",
    },
    vendor: {
      name: "Metro Fresh Supplies",
      id: "VEND-1005",
      phone: "+91 91234 56780",
    },
    products: [
      { name: "Premium Basmati Rice", qty: "600 kg", unitPrice: "₹30", total: "₹18,000" },
      { name: "Saffron Threads", qty: "100 g", unitPrice: "₹20", total: "₹2,000" }
    ],
    priceBreakdown: { subtotal: "₹20,000", tax: "₹1,000", delivery: "₹0", total: "₹21,000" },
    deliveryAddress: "Loading Dock B, The Meridian Hotels, Bandra, Mumbai 400050",
    driver: { name: "Unassigned", phone: "-", vehicle: "-" },
    timeline: [
      { status: "Order Placed", time: "16 Jun 2026, 10:30 AM", note: "Order generated by client." }
    ],
    paymentReference: "-",
    invoiceLink: "#INV-ORD-291",
    notes: "Long grain, aged 2yr preferred. Must deliver before 8am.",
    complaintId: null
  },
  {
    id: "ORD-289",
    date: "15 Jun 2026, 09:15 AM",
    requiredDate: "16 Jun 2026",
    status: "Processing",
    paymentStatus: "Paid",
    deliveryStatus: "In Transit",
    amount: "₹14,500",
    city: "Mumbai",
    owner: {
      name: "Rahul Mehta",
      business: "The Meridian Hotels",
      phone: "+91 98765 43210",
      email: "procurement@meridian.com",
    },
    vendor: {
      name: "Metro Fresh Supplies",
      id: "VEND-1005",
      phone: "+91 91234 56780",
    },
    products: [
      { name: "Sunflower Oil (Refined) – 5L", qty: "20 cans", unitPrice: "₹650", total: "₹13,000" }
    ],
    priceBreakdown: { subtotal: "₹13,000", tax: "₹1,000", delivery: "₹500", total: "₹14,500" },
    deliveryAddress: "Loading Dock B, The Meridian Hotels, Andheri, Mumbai 400053",
    driver: { name: "Ramesh Singh", phone: "+91 99887 76655", vehicle: "MH-01-AB-1234 (Temp Controlled)" },
    timeline: [
      { status: "Order Placed", time: "15 Jun 2026, 09:15 AM", note: "Order generated." },
      { status: "Payment Confirmed", time: "15 Jun 2026, 09:20 AM", note: "Auto-charged wallet." },
      { status: "Processing", time: "15 Jun 2026, 11:00 AM", note: "Vendor preparing items." },
      { status: "In Transit", time: "16 Jun 2026, 07:30 AM", note: "Driver dispatched." }
    ],
    paymentReference: "TXN-9821389",
    invoiceLink: "#INV-ORD-289",
    notes: "Double-filtered, FSSAI certified.",
    complaintId: null
  },
  {
    id: "ORD-287",
    date: "14 Jun 2026, 14:00 PM",
    requiredDate: "15 Jun 2026",
    status: "Delivered",
    paymentStatus: "Paid",
    deliveryStatus: "Delivered",
    amount: "₹78,400",
    city: "Mumbai",
    owner: {
      name: "Rahul Mehta",
      business: "The Meridian Hotels",
      phone: "+91 98765 43210",
      email: "procurement@meridian.com",
    },
    vendor: {
      name: "Pacific Seafood Co.",
      id: "VEND-1022",
      phone: "+91 88888 77777",
    },
    products: [
      { name: "Atlantic Salmon Fillet", qty: "80 kg", unitPrice: "₹900", total: "₹72,000" }
    ],
    priceBreakdown: { subtotal: "₹72,000", tax: "₹3,600", delivery: "₹2,800", total: "₹78,400" },
    deliveryAddress: "Loading Dock A, The Meridian Hotels, Juhu, Mumbai 400049",
    driver: { name: "Abdul Khan", phone: "+91 99887 11111", vehicle: "MH-04-XX-9999 (Refrigerated)" },
    timeline: [
      { status: "Order Placed", time: "14 Jun 2026, 14:00 PM", note: "Order generated." },
      { status: "In Transit", time: "15 Jun 2026, 06:00 AM", note: "Dispatched from cold storage." },
      { status: "Delivered", time: "15 Jun 2026, 09:15 AM", note: "Received by Store Manager." }
    ],
    paymentReference: "TXN-7123992",
    invoiceLink: "#INV-ORD-287",
    notes: "Chilled transport mandatory.",
    complaintId: null
  },
  {
    id: "ORD-283",
    date: "12 Jun 2026, 11:30 AM",
    requiredDate: "13 Jun 2026",
    status: "Disputed",
    paymentStatus: "Refund Pending",
    deliveryStatus: "Delivered",
    amount: "₹8,200",
    city: "Mumbai",
    owner: {
      name: "Karan Mehra",
      business: "The Food Junction",
      phone: "+91 99999 00000",
      email: "admin@foodjunction.in",
    },
    vendor: {
      name: "Metro Fresh Supplies",
      id: "VEND-1005",
      phone: "+91 91234 56780",
    },
    products: [
      { name: "Fresh Vegetables Pack", qty: "200 kg", unitPrice: "₹40", total: "₹8,000" }
    ],
    priceBreakdown: { subtotal: "₹8,000", tax: "₹200", delivery: "₹0", total: "₹8,200" },
    deliveryAddress: "Sector 17, Chandigarh",
    driver: { name: "Suresh", phone: "+91 88811 22222", vehicle: "CH-01-YY-1111" },
    timeline: [
      { status: "Order Placed", time: "12 Jun 2026, 11:30 AM", note: "Order generated." },
      { status: "Delivered", time: "13 Jun 2026, 08:00 AM", note: "Delivered." },
      { status: "Disputed", time: "13 Jun 2026, 09:00 AM", note: "Quality issue raised by client." }
    ],
    paymentReference: "TXN-8822111",
    invoiceLink: "#INV-ORD-283",
    notes: "Client reported spoiled tomatoes.",
    complaintId: "CH-2025-813"
  }
];

const DEFAULT_REQUIREMENTS = [
  {
    id: "REQ-9901",
    owner: {
      name: "Rahul Mehta",
      business: "The Meridian Hotels",
      phone: "+91 98765 43210",
      email: "procurement@meridian.com",
    },
    module: "Manpower",
    type: "Broadcast",
    category: "Chefs / Cooks",
    date: "16 Jun 2026",
    status: "Open",
    details: "Need 2 experienced Executive Chefs for multi-cuisine restaurant. Minimum 5 years experience.",
    targetAgencies: ["All registered manpower agencies in Mumbai"],
    responses: [
      { agency: "Elite Staffing Solutions", date: "16 Jun 2026", status: "Proposal Submitted", notes: "2 candidates available immediately" },
      { agency: "QuickHire Manpower", date: "17 Jun 2026", status: "Reviewed", notes: "1 candidate matching criteria" }
    ],
    selectedAgency: null,
    relatedContext: "New restaurant branch opening in Juhu.",
    timeline: [
      { status: "Open", time: "16 Jun 2026, 10:00 AM", note: "Requirement broadcasted to 15 agencies." }
    ],
    complaintId: null,
    internalNotes: "Prioritize agencies with good replacement policies."
  },
  {
    id: "REQ-9902",
    owner: {
      name: "Karan Mehra",
      business: "The Food Junction",
      phone: "+91 99999 00000",
      email: "admin@foodjunction.in",
    },
    module: "Service Provider",
    type: "Direct",
    category: "Deep Cleaning",
    date: "14 Jun 2026",
    status: "Agency Selected",
    details: "Kitchen deep cleaning and exhaust hood maintenance required.",
    targetAgencies: ["QuickClean Hygiene (VEND-1003)"],
    responses: [
      { agency: "QuickClean Hygiene", date: "14 Jun 2026", status: "Accepted", notes: "Quoted ₹12,000 for full kitchen deep clean." }
    ],
    selectedAgency: "QuickClean Hygiene",
    relatedContext: "Monthly maintenance schedule.",
    timeline: [
      { status: "Open", time: "14 Jun 2026, 09:00 AM", note: "Direct request sent to QuickClean Hygiene." },
      { status: "Responded", time: "14 Jun 2026, 11:30 AM", note: "Agency submitted quote." },
      { status: "Agency Selected", time: "15 Jun 2026, 10:00 AM", note: "Quote accepted by HoReCa owner." }
    ],
    complaintId: null,
    internalNotes: ""
  },
  {
    id: "REQ-9903",
    owner: {
      name: "Arjun Patel",
      business: "Brew & Bites Cafe",
      phone: "+91 88888 22222",
      email: "arjun@brewandbites.in",
    },
    module: "Marketing",
    type: "Broadcast",
    category: "Social Media Management",
    date: "10 Jun 2026",
    status: "In Progress",
    details: "Looking for an agency to handle Instagram and Facebook marketing, including content creation and ad campaigns.",
    targetAgencies: ["All Marketing Agencies"],
    responses: [
      { agency: "Creative Digital Edge", date: "11 Jun 2026", status: "Selected", notes: "Retainer agreed at ₹25,000/month." }
    ],
    selectedAgency: "Creative Digital Edge",
    relatedContext: "Pushing local awareness for new seasonal menu.",
    timeline: [
      { status: "Open", time: "10 Jun 2026, 14:00 PM", note: "Broadcasted." },
      { status: "Agency Selected", time: "12 Jun 2026, 09:00 AM", note: "Creative Digital Edge selected." },
      { status: "In Progress", time: "13 Jun 2026, 10:00 AM", note: "Campaign kick-off." }
    ],
    complaintId: null,
    internalNotes: "Monitor performance closely as agency is new to the platform."
  }
];

const DEFAULT_TICKETS = [
  {
    id: "CH-2025-812",
    category: "Payment Issue",
    priority: "SLA Critical",
    status: "Escalated",
    assignedTo: "Support Rep A",
    date: "16 Jun 2026, 11:20 AM",
    slaTimer: "02:15:00",
    raisedBy: { name: "Rahul Mehta", business: "The Meridian Hotels", phone: "+91 98765 43210", email: "rahul@meridian.com", city: "Mumbai", role: "Owner" },
    against: { name: "HRC HUB Finance", type: "Internal System", businessName: "HRC HUB Payments", role: "Internal System", phone: "+91 22 4567 8900", email: "payouts@hrchub.com" },
    relatedEntity: { type: "Order", id: "ORD-1250" },
    subject: "Payout Delay for Order #ORD-1250",
    description: "Merchant has not received payment for Order #ORD-1250 placed on 12 Jun 2026. Delay exceeds standard 24h cycle.",
    evidence: [
      { name: "bank_statement.pdf", size: "1.2MB", url: "https://example.com/doc1" },
      { name: "order_screenshot.png", size: "450KB", url: "https://example.com/doc2" }
    ],
    messages: [
      { sender: "System", type: "system", text: "Ticket created automatically due to payout delay threshold breach.", time: "16 Jun 2026, 11:20 AM" },
      { sender: "Rahul Mehta", type: "user", text: "I urgently need this payment processed. Please assist.", time: "16 Jun 2026, 11:30 AM" },
      { sender: "Support Rep A", type: "admin", text: "We are escalating this to the finance team.", time: "16 Jun 2026, 11:35 AM" }
    ],
    internalNotes: [
      { sender: "Support Rep A", text: "Finance gateway returned error code 503 during auto-settlement. Manual retry required.", time: "16 Jun 2026, 11:36 AM" }
    ],
    timeline: [
      { status: "Open", time: "16 Jun 2026, 11:20 AM", note: "System auto-flagged delay." },
      { status: "Escalated", time: "16 Jun 2026, 11:35 AM", note: "Escalated to Finance Tier 2." }
    ],
    resolutionSummary: null
  },
  {
    id: "CH-2025-813",
    category: "Product Quality",
    priority: "Medium",
    status: "Investigating",
    assignedTo: "Neha Mathews",
    date: "15 Jun 2026, 09:10 AM",
    slaTimer: "24:00:00",
    raisedBy: { name: "Karan Mehra", business: "The Food Junction", phone: "+91 99999 00000", email: "karan@foodjunction.com", city: "Delhi", role: "Owner" },
    against: { name: "Metro Fresh Supplies", type: "Vendor", id: "VEND-1005", businessName: "Metro Fresh Supplies Ltd", role: "Vendor", phone: "+91 95555 00005", email: "logistics@freshfoods.com" },
    relatedEntity: { type: "Order", id: "ORD-283" },
    subject: "Wrong Coffee Beans Supplied",
    description: "Received whole coffee beans instead of medium-grind powder for stock item CCD-89.",
    evidence: [
      { name: "wrong_item_photo.jpg", size: "2.1MB", url: "https://example.com/doc3" }
    ],
    messages: [
      { sender: "Karan Mehra", type: "user", text: "Please expedite, we are running out of espresso powder.", time: "15 Jun 2026, 09:12 AM" }
    ],
    internalNotes: [
      { sender: "Neha Mathews", text: "Vendor notified. Awaiting their confirmation for replacement dispatch.", time: "15 Jun 2026, 09:30 AM" }
    ],
    timeline: [
      { status: "Open", time: "15 Jun 2026, 09:10 AM", note: "User opened ticket." },
      { status: "Assigned", time: "15 Jun 2026, 09:15 AM", note: "Assigned to Neha Mathews." },
      { status: "Investigating", time: "15 Jun 2026, 09:30 AM", note: "Checking with vendor." }
    ],
    resolutionSummary: null
  },
  {
    id: "CH-2025-815",
    category: "Service Issue",
    priority: "High",
    status: "Waiting for User",
    assignedTo: "Unassigned",
    date: "14 Jun 2026, 02:00 PM",
    slaTimer: "12:30:00",
    raisedBy: { name: "Arjun Patel", business: "Brew & Bites Cafe", phone: "+91 88888 22222", email: "arjun@brewbites.com", city: "Bangalore", role: "Owner" },
    against: { name: "QuickClean Hygiene", type: "Service Provider", id: "VEND-1003", businessName: "QuickClean Hygiene Services", role: "Service Provider", phone: "+91 88888 00003", email: "clean@quickclean.in" },
    relatedEntity: { type: "Requirement", id: "REQ-9902" },
    subject: "Deep Cleaning Agency No-Show",
    description: "The deep cleaning agency did not show up at the scheduled time of 10 AM.",
    evidence: [],
    messages: [
      { sender: "Arjun Patel", type: "user", text: "No one answered the phone when I called them.", time: "14 Jun 2026, 02:00 PM" },
      { sender: "System", type: "system", text: "Automated message sent to QuickClean Hygiene requesting status.", time: "14 Jun 2026, 02:05 PM" }
    ],
    internalNotes: [],
    timeline: [
      { status: "Open", time: "14 Jun 2026, 02:00 PM", note: "User opened ticket." },
      { status: "Waiting for User", time: "14 Jun 2026, 02:10 PM", note: "Requested CCTV snapshot from HoReCa owner to confirm no-show." }
    ],
    resolutionSummary: null
  },
  {
    id: "CH-2025-816",
    category: "Manpower Issue",
    priority: "Low",
    status: "Resolved",
    assignedTo: "Sarah Connor",
    date: "13 Jun 2026, 10:00 AM",
    slaTimer: "00:00:00",
    raisedBy: { name: "Vijay Shah", business: "Royal Palace Hotel", phone: "+91 97777 55555", email: "vijay@royalpalace.com", city: "Pune", role: "Owner" },
    against: { name: "Elite Staffing Solutions", type: "Manpower Agency", id: "VEND-1002", businessName: "Elite Manpower & Staffing", role: "Manpower Agency", phone: "+91 91234 00002", email: "contact@elitestaffing.in" },
    relatedEntity: { type: "Requirement", id: "REQ-1014" },
    subject: "Chef replacement delayed",
    description: "Replacement cook was not sent within the promised 24 hours timeline.",
    evidence: [],
    messages: [
      { sender: "Vijay Shah", type: "user", text: "Please help us, we are down one chef in the kitchen today.", time: "13 Jun 2026, 10:00 AM" },
      { sender: "Sarah Connor", type: "admin", text: "We have contacted Elite Staffing. They are sending a replacement by 1 PM.", time: "13 Jun 2026, 10:30 AM" }
    ],
    internalNotes: [
      { sender: "Sarah Connor", text: "Elite Staffing confirmed the replacement candidate is on the way.", time: "13 Jun 2026, 10:25 AM" }
    ],
    timeline: [
      { status: "Open", time: "13 Jun 2026, 10:00 AM", note: "User opened ticket." },
      { status: "Assigned", time: "13 Jun 2026, 10:05 AM", note: "Assigned to Sarah Connor." },
      { status: "Resolved", time: "13 Jun 2026, 12:45 PM", note: "Replacement cook arrived. User confirmed service resumed." }
    ],
    resolutionSummary: "Cook replacement dispatched and arrived at 12:40 PM. Verified with hotel owner."
  }
];

const DEFAULT_KYC = [
  {
    id: "KYC-1099",
    businessName: "Demo Cafe & Restro",
    type: "Cafe",
    entityType: "HoReCa Owners",
    proprietor: "Sanjay Kumar",
    location: "Pune",
    dateSubmitted: "16 Jul 2026, 04:30 PM",
    status: "Pending",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Unassigned",
    history: [],
    notes: "New demo record added as requested.",
    fssaiNumber: "FSSAI-DEMO-123",
    gstinNumber: "27DEMO1234H1Z5",
    panNumber: "DEMOPAN123",
    businessLicense: "LIC-DEMO-44",
    propertyPhotos: "2 uploaded"
  },
  {
    id: "KYC-1024",
    businessName: "Hotel Blue Sapphire",
    type: "Hotel",
    entityType: "HoReCa Owners",
    proprietor: "Rahul Mehta",
    location: "Mumbai",
    dateSubmitted: "24 May 2026, 10:50 AM",
    status: "Pending",
    documentCompletion: "80%",
    riskFlag: "Low",
    adminAssigned: "Unassigned",
    history: [],
    notes: "",
    fssaiNumber: "FSSAI-122456708912",
    gstinNumber: "27AABCB1234H1Z5",
    panNumber: "AABCB1234H",
    businessLicense: "LIC-MUM-49281",
    propertyPhotos: "3 uploaded"
  },
  {
    id: "KYC-1031",
    businessName: "Spice Route Kitchen",
    type: "Restaurant",
    entityType: "HoReCa Owners",
    proprietor: "Ajay Verma",
    location: "Delhi",
    dateSubmitted: "28 May 2026, 03:15 PM",
    status: "Pending",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Unassigned",
    history: [],
    notes: "Famous local dining spot. Docs look clear.",
    fssaiNumber: "FSSAI-224455889900",
    gstinNumber: "07AAACV8821B1Z9",
    panNumber: "AAACV8821B",
    businessLicense: "LIC-DEL-8812",
    propertyPhotos: "4 uploaded"
  },
  {
    id: "KYC-1032",
    businessName: "Royal Orchid Hotel",
    type: "Hotel",
    entityType: "HoReCa Owners",
    proprietor: "Ramesh Kumar",
    location: "Mumbai",
    dateSubmitted: "29 May 2026, 11:00 AM",
    status: "Approved",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Neha Mathews",
    history: [{ status: "Pending", date: "28 May 2026" }, { status: "Approved", date: "29 May 2026" }],
    notes: "Premium 5-star hotel branch. All documents verified.",
    fssaiNumber: "FSSAI-556677889900",
    gstinNumber: "27AABCR5512D1Z2",
    panNumber: "AABCR5512D",
    businessLicense: "LIC-MUM-77231",
    propertyPhotos: "5 uploaded"
  },
  {
    id: "KYC-1033",
    businessName: "Brew & Bites Cafe",
    type: "Cafe",
    entityType: "HoReCa Owners",
    proprietor: "Arjun Patel",
    location: "Bangalore",
    dateSubmitted: "30 May 2026, 04:20 PM",
    status: "Approved",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Super Admin",
    history: [{ status: "Pending", date: "29 May 2026" }, { status: "Approved", date: "30 May 2026" }],
    notes: "Popular local cafe outlet.",
    fssaiNumber: "FSSAI-112233445566",
    gstinNumber: "29BBDCP1122A1Z1",
    panNumber: "BBDCP1122A",
    businessLicense: "LIC-BLR-9921",
    propertyPhotos: "3 uploaded"
  },
  {
    id: "KYC-1025",
    businessName: "Fresh Farms Dairy",
    type: "Supplier",
    entityType: "Raw Material Vendors",
    proprietor: "Suresh Das",
    location: "Delhi",
    dateSubmitted: "24 May 2026, 08:30 AM",
    status: "Under Review",
    documentCompletion: "100%",
    riskFlag: "Medium",
    adminAssigned: "Neha Mathews",
    history: [{ status: "Pending", date: "23 May 2026" }],
    notes: "Awaiting warehouse verification.",
    fssaiNumber: "FSSAI-108746283941",
    gstinNumber: "07AAACG8472K1Z3",
    panNumber: "AAACG8472K",
    warehouseDetails: "Okhla Industrial Area Phase II",
    productCategories: "Dairy, Milk Products"
  },
  {
    id: "KYC-1034",
    businessName: "Metro Fresh Supplies",
    type: "Supplier",
    entityType: "Raw Material Vendors",
    proprietor: "Vikrant Mehta",
    location: "Mumbai",
    dateSubmitted: "01 Jun 2026, 09:30 AM",
    status: "Pending",
    documentCompletion: "90%",
    riskFlag: "Low",
    adminAssigned: "Unassigned",
    history: [],
    notes: "Large vegetable supplier. Awaiting warehouse visit.",
    fssaiNumber: "FSSAI-334455667788",
    gstinNumber: "27AABCM3344M1Z4",
    panNumber: "AABCM3344M",
    warehouseDetails: "Vashi APMC Market, Navi Mumbai",
    productCategories: "Fruits, Vegetables, Fresh Produce"
  },
  {
    id: "KYC-1026",
    businessName: "Elite Staffing Solutions",
    type: "Agency",
    entityType: "Manpower Agencies",
    proprietor: "Kavita Sharma",
    location: "Bangalore",
    dateSubmitted: "25 May 2026, 11:15 AM",
    status: "Approved",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Super Admin",
    history: [{ status: "Pending", date: "20 May 2026" }, { status: "Approved", date: "25 May 2026" }],
    notes: "Verified all references.",
    gstinNumber: "29BBDCG9022M2Z1",
    panNumber: "BBDCG9022M",
    labourLicence: "LAB-KA-88124",
    agencyRegistration: "REG-2023-BGLR",
    replacementPolicy: "48-hour replacement guarantee"
  },
  {
    id: "KYC-1035",
    businessName: "QuickHire Manpower",
    type: "Agency",
    entityType: "Manpower Agencies",
    proprietor: "Rajesh Gond",
    location: "Mumbai",
    dateSubmitted: "02 Jun 2026, 01:10 PM",
    status: "Under Review",
    documentCompletion: "100%",
    riskFlag: "Medium",
    adminAssigned: "Neha Mathews",
    history: [{ status: "Pending", date: "02 Jun 2026" }],
    notes: "Background screening in progress.",
    gstinNumber: "27AABCQ7722N1Z8",
    panNumber: "AABCQ7722N",
    labourLicence: "LAB-MH-55212",
    agencyRegistration: "REG-2024-MUM",
    replacementPolicy: "7-day replacement window"
  },
  {
    id: "KYC-1027",
    businessName: "CoolBreeze HVAC Tech",
    type: "Contractor",
    entityType: "Service Providers",
    proprietor: "Vikram Singh",
    location: "Pune",
    dateSubmitted: "26 May 2026, 02:40 PM",
    status: "Under Review",
    documentCompletion: "60%",
    riskFlag: "High",
    adminAssigned: "Neha Mathews",
    history: [{ status: "Pending", date: "26 May 2026" }],
    notes: "Service certification expired.",
    gstinNumber: "27CCXPC1456P1Z3",
    panNumber: "CCXPC1456P",
    serviceCertifications: "ISO 9001 (Expired)",
    teamDetails: "12 Certified Technicians",
    coverageAreas: "Pune, Pimpri-Chinchwad"
  },
  {
    id: "KYC-1036",
    businessName: "QuickClean Hygiene",
    type: "Contractor",
    entityType: "Service Providers",
    proprietor: "Harish Rao",
    location: "Bangalore",
    dateSubmitted: "03 Jun 2026, 11:45 AM",
    status: "Approved",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Super Admin",
    history: [{ status: "Pending", date: "02 Jun 2026" }, { status: "Approved", date: "03 Jun 2026" }],
    notes: "Top cleaning vendor. Good credentials.",
    gstinNumber: "29BBDCQ5511K1Z7",
    panNumber: "BBDCQ5511K",
    serviceCertifications: "ISO 9001:2015, WHO Cleaning Standards",
    teamDetails: "45 Trained Personnel",
    coverageAreas: "Bangalore Urban, Bangalore Rural"
  },
  {
    id: "KYC-1028",
    businessName: "Creative Digital Edge",
    type: "Agency",
    entityType: "Marketing Agencies",
    proprietor: "Anita Desai",
    location: "Mumbai",
    dateSubmitted: "27 May 2026, 09:20 AM",
    status: "Pending",
    documentCompletion: "100%",
    riskFlag: "Low",
    adminAssigned: "Unassigned",
    history: [],
    notes: "",
    gstinNumber: "27DDEFR4567R1Z4",
    panNumber: "DDEFR4567R",
    portfolio: "www.creativedigitaledge.com/portfolio",
    agencyRegistration: "MUM-MAR-2024-91",
    services: "Social Media, Content Creation, Offline PR"
  },
  {
    id: "KYC-1037",
    businessName: "Creative Marketing Agency",
    type: "Agency",
    entityType: "Marketing Agencies",
    proprietor: "Divya Nair",
    location: "Delhi",
    dateSubmitted: "04 Jun 2026, 02:20 PM",
    status: "Rejected",
    documentCompletion: "50%",
    riskFlag: "High",
    adminAssigned: "Neha Mathews",
    history: [{ status: "Pending", date: "04 Jun 2026" }, { status: "Rejected", date: "05 Jun 2026" }],
    notes: "Invalid GST Certificate submitted. Canceled after no response to change requests.",
    gstinNumber: "07AAACK1122D1Z0 (Invalid)",
    panNumber: "AAACK1122D",
    portfolio: "No active portfolio",
    agencyRegistration: "DEL-MAR-2023-41",
    services: "Branding, Leaflet Printing"
  }
];

const DEFAULT_FEED_ITEMS = [
  {
    id: "fw-01", orderId: "ORD-M001", category: "manpower", title: "Weekend Banquet Servers – 10 persons",
    description: "Need 10 trained servers for Saturday evening gala dinner. 6PM–midnight shift. Formal attire mandatory. Experience in fine dining essential.",
    businessName: "The Meridian Grand", businessType: "Hotel", location: "Bandra, Mumbai",
    qty: "10 persons", date: "21 Jun 2026", budget: "₹20,000", tags: ["Fine Dining", "Weekend", "Formal"],
    status: "New", postedAt: "5 min ago", urgency: "Urgent"
  },
  {
    id: "fw-02", orderId: "ORD-M002", category: "manpower", title: "Head Chef – Italian Cuisine (Long Term)",
    description: "Seeking experienced Head Chef specialising in Italian cuisine. Min 5yr experience. Pasta, risotto, wood-fired pizza expertise required. Trial shift before confirmation.",
    businessName: "Trattoria Milano", businessType: "Restaurant", location: "Colaba, Mumbai",
    qty: "1 person", date: "25 Jun 2026", budget: "₹65,000/mo", tags: ["Head Chef", "Italian", "Long Term"],
    status: "Pending", postedAt: "2 hrs ago", urgency: "Normal"
  },
  {
    id: "fw-03", orderId: "ORD-M003", category: "manpower", title: "Barista – Part-time (Weekends Only)",
    description: "Looking for a skilled barista for weekend shifts (Sat & Sun, 8AM–4PM). Latte art essential. English proficiency required.",
    businessName: "Café Zephyr Group", businessType: "Café", location: "Lower Parel, Mumbai",
    qty: "2 persons", date: "22 Jun 2026", budget: "₹7,200", tags: ["Barista", "Part-time", "Coffee"],
    status: "New", postedAt: "3 hrs ago", urgency: "Normal"
  },
  {
    id: "fw-04", orderId: "ORD-M004", category: "manpower", title: "Security Guards – Night Shift",
    description: "Require 2 security guards for night shift (10PM–6AM). Ex-military or retired police preferred. CCTV monitoring experience required.",
    businessName: "Azure Palace Hotel", businessType: "Hotel", location: "Juhu, Mumbai",
    qty: "2 persons", date: "20 Jun 2026", budget: "₹36,000/mo", tags: ["Security", "Night Shift", "Hotel"],
    status: "Proposal Sent", postedAt: "Yesterday", urgency: "Normal"
  },
  {
    id: "fw-05", orderId: "ORD-S001", category: "service", title: "HVAC Annual Maintenance – 22 Units",
    description: "Full annual maintenance contract for 22 HVAC units across 4 floors. Includes quarterly filter replacement and emergency call-out within 4 hours.",
    businessName: "Sunset Resort", businessType: "Hotel", location: "Versova, Mumbai",
    qty: "22 units / 12 months", date: "25 Jun 2026", budget: "₹85,000/yr", tags: ["HVAC", "AMC", "Annual Contract"],
    status: "New", postedAt: "1 hr ago", urgency: "Normal"
  },
  {
    id: "fw-06", orderId: "ORD-S002", category: "service", title: "Commercial Kitchen Deep Cleaning (3 Sections)",
    description: "Overnight deep clean required for 3 kitchen sections. Must use FSSAI-approved food-safe chemicals only. Work window: 12AM–5AM.",
    businessName: "The Meridian Grand", businessType: "Hotel", location: "Bandra, Mumbai",
    qty: "3 kitchen sections", date: "20 Jun 2026", budget: "₹22,000", tags: ["Deep Clean", "Overnight", "FSSAI"],
    status: "Pending", postedAt: "4 hrs ago", urgency: "Urgent"
  },
  {
    id: "fw-07", orderId: "ORD-S003", category: "service", title: "Monthly Pest Control – Full Property",
    description: "FSSAI-compliant rodent and cockroach treatment for full restaurant premises. Certified pest control agency only. Child and food-safe chemicals mandatory.",
    businessName: "Spice Route Restaurant", businessType: "Restaurant", location: "Andheri, Mumbai",
    qty: "Full property", date: "22 Jun 2026", budget: "₹4,800", tags: ["Pest Control", "FSSAI", "Monthly"],
    status: "New", postedAt: "6 hrs ago", urgency: "Normal"
  },
  {
    id: "fw-08", orderId: "ORD-S004", category: "service", title: "Electrical Wiring Audit & Repair",
    description: "Complete electrical audit of kitchen and dining area. Identify and repair faults. Must be a licensed electrical contractor. Compliance certificate required on completion.",
    businessName: "Café Zephyr Group", businessType: "Café", location: "Lower Parel, Mumbai",
    qty: "Full property", date: "24 Jun 2026", budget: "₹12,000", tags: ["Electrical", "Licensed", "Audit"],
    status: "Accepted", postedAt: "2 days ago", urgency: "Normal"
  },
  {
    id: "fw-09", orderId: "ORD-K001", category: "marketing", title: "July Social Media Campaign – 30 Days",
    description: "Full social media management for July. 12 Reels + 20 static posts for Instagram & Facebook. Food-forward aesthetic. Influencer collaboration preferred.",
    businessName: "Azure Palace Hotel", businessType: "Hotel", location: "Juhu, Mumbai",
    qty: "30 days", date: "01 Jul 2026", budget: "₹40,000", tags: ["Social Media", "Instagram", "Reels"],
    status: "New", postedAt: "30 min ago", urgency: "Normal"
  },
  {
    id: "fw-10", orderId: "ORD-K002", category: "marketing", title: "Complete Menu Photography – 82 Items",
    description: "Professional food photography for full menu (82 dishes). Dark-wood table styling preferred. Natural light setup. RAW files + retouched JPEGs. Delivery within 5 working days.",
    businessName: "Spice Route Restaurant", businessType: "Restaurant", location: "Andheri, Mumbai",
    qty: "82 menu items", date: "26 Jun 2026", budget: "₹18,000", tags: ["Photography", "Menu", "Food Styling"],
    status: "Proposal Sent", postedAt: "Yesterday", urgency: "Normal"
  },
  {
    id: "fw-11", orderId: "ORD-K003", category: "marketing", title: "Google Ads Campaign – 3 Months",
    description: "Search + Display Ads setup and management for 3 months. Focus on reservation conversions. ₹8,000/month ad spend handled by client. ROI reporting monthly.",
    businessName: "The Grand Bistro", businessType: "Restaurant", location: "Fort, Mumbai",
    qty: "3 months", date: "01 Jul 2026", budget: "₹24,000", tags: ["Google Ads", "PPC", "ROI"],
    status: "New", postedAt: "5 hrs ago", urgency: "Urgent"
  },
  {
    id: "fw-12", orderId: "ORD-K004", category: "marketing", title: "Influencer Campaign – 5 Micro Creators",
    description: "Coordinate 5 food-lifestyle micro-influencers (20K–100K followers). Reels + stories. Full content calendar and deliverables list to be submitted before execution.",
    businessName: "Café Zephyr Group", businessType: "Café", location: "Lower Parel, Mumbai",
    qty: "5 creators", date: "28 Jun 2026", budget: "₹42,000", tags: ["Influencer", "Micro", "Content"],
    status: "Accepted", postedAt: "2 days ago", urgency: "Normal"
  }
];

const DEFAULT_HORECA = [
  {
    id: "HR-9901",
    businessName: "Royal Orchid Hotel",
    type: "Hotel",
    owner: "Ramesh Kumar",
    city: "Mumbai",
    rating: 4.8,
    orders: 142,
    joinedDate: "12 Jan 2023",
    verification: "Approved",
    accountStatus: "Active",
    locations: "Bandra West, Colaba",
    documents: "All Documents Verified",
    requirements: "3 Pending Requirements",
    complaints: "0 Open Complaints",
    activityHistory: [
      { action: "Business Registered", date: "12 Jan 2023" },
      { action: "KYC Submitted", date: "15 Jan 2023" },
      { action: "Verified", date: "20 Jan 2023" },
      { action: "First Order Placed", date: "25 Jan 2023" }
    ],
    phone: "+91 98765 43210",
    email: "ramesh@royalorchid.com",
    address: "Bandra West, Mumbai, 400050",
    gstNumber: "27AABCR5512D1Z2",
    fssaiNumber: "11223344556677",
    profileCompletion: 100,
    completedOrders: 138,
    revenue: "₹18,40,000",
    licenseExpiry: "15 Dec 2028",
    licenseStatus: "Valid"
  },
  {
    id: "HR-9902",
    businessName: "Spice Route Kitchen",
    type: "Restaurant",
    owner: "Ajay Verma",
    city: "Delhi",
    rating: 4.5,
    orders: 89,
    joinedDate: "24 Mar 2024",
    verification: "Pending",
    accountStatus: "Active",
    locations: "Connaught Place",
    documents: "FSSAI Missing",
    requirements: "No Open Requirements",
    complaints: "1 Open Complaint",
    activityHistory: [
      { action: "Business Registered", date: "24 Mar 2024" },
      { action: "KYC Submitted", date: "26 Mar 2024" }
    ],
    phone: "+91 91234 56789",
    email: "ajay@spiceroute.com",
    address: "Connaught Place, New Delhi, 110001",
    gstNumber: "07AAACV8821B1Z9",
    fssaiNumber: "22334455667788",
    profileCompletion: 85,
    completedOrders: 80,
    revenue: "₹6,80,000",
    licenseExpiry: "10 Oct 2026",
    licenseStatus: "Expiring Soon"
  },
  {
    id: "HR-9903",
    businessName: "Brew & Bites Cafe",
    type: "Cafe",
    owner: "Arjun Patel",
    city: "Bangalore",
    rating: 4.9,
    orders: 310,
    joinedDate: "05 Nov 2022",
    verification: "Approved",
    accountStatus: "Active",
    locations: "Indiranagar",
    documents: "All Documents Verified",
    requirements: "Looking for Barista",
    complaints: "0 Open Complaints",
    activityHistory: [
      { action: "Business Registered", date: "05 Nov 2022" },
      { action: "KYC Submitted", date: "08 Nov 2022" },
      { action: "Verified", date: "15 Nov 2022" },
      { action: "First Order Placed", date: "20 Nov 2022" }
    ],
    phone: "+91 88888 22222",
    email: "arjun@brewandbites.in",
    address: "Indiranagar, Bangalore, 560038",
    gstNumber: "29BBDCP1122A1Z1",
    fssaiNumber: "33445566778899",
    profileCompletion: 95,
    completedOrders: 305,
    revenue: "₹24,50,000",
    licenseExpiry: "05 Nov 2027",
    licenseStatus: "Valid"
  },
  {
    id: "HR-9904",
    businessName: "The Food Junction",
    type: "Restaurant",
    owner: "Karan Mehra",
    city: "Chandigarh",
    rating: 4.2,
    orders: 45,
    joinedDate: "10 Jun 2025",
    verification: "Approved",
    accountStatus: "Suspended",
    locations: "Sector 17",
    documents: "All Documents Verified",
    requirements: "None",
    complaints: "3 Escalated Complaints",
    activityHistory: [
      { action: "Business Registered", date: "10 Jun 2025" },
      { action: "KYC Submitted", date: "12 Jun 2025" },
      { action: "Verified", date: "20 Jun 2025" }
    ],
    phone: "+91 99999 00000",
    email: "admin@foodjunction.in",
    address: "Sector 17, Chandigarh, 160017",
    gstNumber: "04AAACK8822C1Z4",
    fssaiNumber: "44556677889900",
    profileCompletion: 100,
    completedOrders: 40,
    revenue: "₹3,20,000",
    licenseExpiry: "12 Mar 2026",
    licenseStatus: "Expired"
  }
];

const DEFAULT_VENDORS = [
  {
    id: "VEND-1001",
    name: "Green Valley Supplies",
    businessName: "Green Valley Supplies Ltd",
    category: "Raw Material",
    city: "Mumbai",
    rating: 4.8,
    verification: "Approved",
    accountStatus: "Active",
    joinedDate: "10 Feb 2023",
    productCount: 150,
    totalOrders: 1248,
    onTimeDelivery: "98%",
    isTopRated: true,
    documentStatus: "Valid",
    phone: "+91 98765 00001",
    email: "info@greenvalley.com",
    ownerName: "Rajesh Sharma",
    serviceArea: "Mumbai MMR, Pune",
    profileCompletion: 95,
    completedOrders: 1210,
    successRate: "98%",
    documents: [
      { name: "PAN", status: "Valid", expiryDate: "N/A" },
      { name: "GST", status: "Valid", expiryDate: "10 Feb 2029" },
      { name: "Trade License", status: "Valid", expiryDate: "15 Dec 2028" },
      { name: "Bank Proof", status: "Valid", expiryDate: "N/A" }
    ],
    productCategories: "Vegetables, Fruits, Grains",
    deliveryArea: "Mumbai MMR",
    stockAvailability: "95% In Stock"
  },
  {
    id: "VEND-1002",
    name: "Elite Staffing Solutions",
    businessName: "Elite Manpower & Staffing",
    category: "Manpower",
    city: "Delhi",
    rating: 4.6,
    verification: "Approved",
    accountStatus: "Active",
    joinedDate: "22 May 2024",
    candidateCount: 450,
    activeDeployments: 120,
    placementRate: "92%",
    replacementRate: "5%",
    isTopRated: false,
    documentStatus: "Expiring Soon",
    phone: "+91 91234 00002",
    email: "contact@elitestaffing.in",
    ownerName: "Sanjay Singhal",
    serviceArea: "Delhi NCR, Noida, Gurugram",
    profileCompletion: 85,
    completedOrders: 340,
    successRate: "92%",
    documents: [
      { name: "PAN", status: "Valid", expiryDate: "N/A" },
      { name: "GST", status: "Valid", expiryDate: "15 Jan 2028" },
      { name: "Trade License", status: "Expiring Soon", expiryDate: "10 Aug 2026" },
      { name: "Bank Proof", status: "Valid", expiryDate: "N/A" }
    ],
    availableStaff: "150 Cooks, 120 Waiters, 80 Cleaners",
    staffRoles: "Chef, Waiter, Kitchen Helper, Barista",
    placementCount: 340
  },
  {
    id: "VEND-1003",
    name: "QuickClean Hygiene",
    businessName: "QuickClean Hygiene Services",
    category: "Service Provider",
    city: "Bangalore",
    rating: 4.9,
    verification: "Approved",
    accountStatus: "Active",
    joinedDate: "15 Aug 2022",
    serviceCount: 12,
    teamSize: 85,
    activeJobs: 34,
    completionRate: "99%",
    reworkRate: "1%",
    isTopRated: true,
    documentStatus: "Valid",
    phone: "+91 88888 00003",
    email: "clean@quickclean.in",
    ownerName: "Anita Reddy",
    serviceArea: "Bangalore Urban, Bangalore Rural",
    profileCompletion: 100,
    completedOrders: 512,
    successRate: "99%",
    documents: [
      { name: "PAN", status: "Valid", expiryDate: "N/A" },
      { name: "GST", status: "Valid", expiryDate: "05 Nov 2029" },
      { name: "Trade License", status: "Valid", expiryDate: "30 Sep 2028" },
      { name: "Bank Proof", status: "Valid", expiryDate: "N/A" }
    ],
    serviceCategories: "Deep Cleaning, Pest Control, Sanitization",
    completedServices: 512,
    serviceAreas: "Bangalore District"
  },
  {
    id: "VEND-1004",
    name: "Creative Digital Edge",
    businessName: "Creative Digital Edge Agency",
    category: "Marketing Agency",
    city: "Mumbai",
    rating: 4.5,
    verification: "Pending",
    accountStatus: "Suspended",
    joinedDate: "05 Jan 2026",
    serviceType: "Social Media & SEO",
    activeCampaigns: 4,
    completedCampaigns: 12,
    teamSize: 15,
    isTopRated: false,
    documentStatus: "Expired",
    phone: "+91 99999 00004",
    email: "hello@creativedigital.com",
    ownerName: "Vikram Malhotra",
    serviceArea: "Online, Pan India",
    profileCompletion: 70,
    completedOrders: 12,
    successRate: "85%",
    documents: [
      { name: "PAN", status: "Valid", expiryDate: "N/A" },
      { name: "GST", status: "Expired", expiryDate: "12 May 2026" },
      { name: "Trade License", status: "Expired", expiryDate: "30 Jun 2026" },
      { name: "Bank Proof", status: "Valid", expiryDate: "N/A" }
    ],
    portfolioCount: 15
  },
  {
    id: "VEND-1005",
    name: "Fresh Foods Logistics",
    businessName: "Fresh Foods Logistics Pvt Ltd",
    category: "Raw Material",
    city: "Pune",
    rating: 4.2,
    verification: "Rejected",
    accountStatus: "Blocked",
    joinedDate: "11 Mar 2025",
    productCount: 85,
    totalOrders: 412,
    onTimeDelivery: "91%",
    isTopRated: false,
    documentStatus: "Valid",
    phone: "+91 95555 00005",
    email: "logistics@freshfoods.com",
    ownerName: "Manoj Deshmukh",
    serviceArea: "Pune, Pimpri Chinchwad",
    profileCompletion: 80,
    completedOrders: 410,
    successRate: "91%",
    documents: [
      { name: "PAN", status: "Valid", expiryDate: "N/A" },
      { name: "GST", status: "Valid", expiryDate: "11 Mar 2030" },
      { name: "Trade License", status: "Valid", expiryDate: "31 Dec 2029" },
      { name: "Bank Proof", status: "Valid", expiryDate: "N/A" }
    ],
    productCategories: "Dairy, Frozen Foods, Poultry",
    deliveryArea: "Pune Region",
    stockAvailability: "88% In Stock"
  }
];

const DEFAULT_CATEGORIES = [
  { id: "CAT-001", name: "Dairy & Milk", parent: "-", module: "Raw Material Categories", order: 1, usage: 145, status: "Active", updated: "10 Jun 2026" },
  { id: "CAT-002", name: "Cheese", parent: "Dairy & Milk", module: "Raw Material Subcategories", order: 1, usage: 82, status: "Active", updated: "12 Jun 2026" },
  { id: "CAT-003", name: "Executive Chef", parent: "-", module: "Manpower Roles", order: 1, usage: 45, status: "Active", updated: "05 Jun 2026" },
  { id: "CAT-004", name: "Deep Cleaning", parent: "-", module: "Service Provider Categories", order: 2, usage: 120, status: "Active", updated: "15 Jun 2026" },
  { id: "CAT-005", name: "Social Media Management", parent: "-", module: "Marketing Online Services", order: 1, usage: 34, status: "Active", updated: "08 Jun 2026" },
  { id: "CAT-006", name: "Billboard Advertising", parent: "-", module: "Marketing Offline Services", order: 3, usage: 0, status: "Inactive", updated: "01 Jun 2026" },
  { id: "CAT-007", name: "Exotic Meats", parent: "-", module: "Raw Material Categories", order: 99, usage: 2, status: "Archived", updated: "10 Jan 2026" },
];

const DEFAULT_ADMINS = [
  { id: "ADM-001", name: "Sarah Connor", email: "sarah@hrchub.com", phone: "+91 99999 11111", role: "Super Admin", access: ["Verification", "Directory", "Vendors", "Orders", "Requirements", "Complaints", "Categories", "Limits", "Team"], status: "Active", isOnline: true, lastLogin: "Just now" },
  { id: "ADM-002", name: "John Smith", email: "john@hrchub.com", phone: "+91 99999 22222", role: "Verification Admin", access: ["Verification", "Directory", "Vendors"], status: "Active", isOnline: false, lastLogin: "2 hours ago" },
  { id: "ADM-003", name: "Neha Mathews", email: "neha@hrchub.com", phone: "+91 99999 33333", role: "Support Admin", access: ["Complaints", "Directory", "Vendors", "Limits"], status: "Active", isOnline: true, lastLogin: "15 mins ago" },
  { id: "ADM-004", name: "Raj Patel", email: "raj@hrchub.com", phone: "+91 99999 44444", role: "Operations Admin", access: ["Orders", "Requirements", "Categories"], status: "Disabled", isOnline: false, lastLogin: "14 May 2026" },
  { id: "ADM-005", name: "Amit Desai", email: "amit@hrchub.com", phone: "+91 99999 55555", role: "Read-Only Auditor", access: ["Verification", "Directory", "Vendors", "Orders", "Requirements", "Complaints", "Limits"], status: "Pending", isOnline: false, lastLogin: "Never" }
];

export const mockDb = {
  init: () => {
    let resetOrders = false;
    try {
      const existing = localStorage.getItem("hrchub_orders");
      if (existing) {
        const parsed = JSON.parse(existing);
        if (parsed.length > 0 && (!parsed[0].vendor || !parsed[0].client || !parsed[0].category)) {
          resetOrders = true;
        }
      }
    } catch (e) {
      resetOrders = true;
    }

    if (!localStorage.getItem("hrchub_orders") || resetOrders) {
      localStorage.setItem("hrchub_orders", JSON.stringify(DEFAULT_ORDERS));
    } else {
      try {
        const existing = localStorage.getItem("hrchub_orders");
        if (existing) {
          const parsed = JSON.parse(existing);
          const filtered = parsed.filter((o) => o.id !== "ORD-952");
          if (filtered.length !== parsed.length) {
            localStorage.setItem("hrchub_orders", JSON.stringify(filtered));
          }
        }
      } catch (e) { }
    }
    let resetTickets = false;
    try {
      const existing = localStorage.getItem("hrchub_tickets");
      if (existing) {
        const parsed = JSON.parse(existing);
        if (parsed.length > 0 && !parsed[0].subject) {
          resetTickets = true;
        }
      }
    } catch (e) {
      resetTickets = true;
    }

    if (!localStorage.getItem("hrchub_tickets") || resetTickets) {
      localStorage.setItem("hrchub_tickets", JSON.stringify(DEFAULT_TICKETS));
    }
    if (!localStorage.getItem("hrchub_kyc")) {
      localStorage.setItem("hrchub_kyc", JSON.stringify(DEFAULT_KYC));
    } else {
      try {
        const existingKyc = JSON.parse(localStorage.getItem("hrchub_kyc"));
        let updated = false;
        DEFAULT_KYC.forEach(item => {
          if (!existingKyc.some(k => k.id === item.id)) {
            existingKyc.push(item);
            updated = true;
          }
        });
        if (updated) {
          localStorage.setItem("hrchub_kyc", JSON.stringify(existingKyc));
        }
      } catch (e) { }
    }
    if (!localStorage.getItem("hrchub_feed")) {
      localStorage.setItem("hrchub_feed", JSON.stringify(DEFAULT_FEED_ITEMS));
    }
    let resetHoreca = false;
    try {
      const existing = localStorage.getItem("hrchub_horeca");
      if (existing) {
        const parsed = JSON.parse(existing);
        if (parsed.length > 0 && !parsed[0].gstNumber) {
          resetHoreca = true;
        }
      }
    } catch (e) {
      resetHoreca = true;
    }

    if (!localStorage.getItem("hrchub_horeca") || resetHoreca) {
      localStorage.setItem("hrchub_horeca", JSON.stringify(DEFAULT_HORECA));
    }
    let resetVendors = false;
    try {
      const existing = localStorage.getItem("hrchub_vendors");
      if (existing) {
        const parsed = JSON.parse(existing);
        if (parsed.length > 0 && !parsed[0].businessName) {
          resetVendors = true;
        }
      }
    } catch (e) {
      resetVendors = true;
    }

    if (!localStorage.getItem("hrchub_vendors") || resetVendors) {
      localStorage.setItem("hrchub_vendors", JSON.stringify(DEFAULT_VENDORS));
    }
    if (!localStorage.getItem("hrchub_requirements")) {
      localStorage.setItem("hrchub_requirements", JSON.stringify(DEFAULT_REQUIREMENTS));
    }
    if (!localStorage.getItem("hrchub_categories")) {
      localStorage.setItem("hrchub_categories", JSON.stringify(DEFAULT_CATEGORIES));
    }
    if (!localStorage.getItem("hrchub_admins")) {
      localStorage.setItem("hrchub_admins", JSON.stringify(DEFAULT_ADMINS));
    }
  },

  getOrders: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_orders") || "[]");
  },

  saveOrders: (orders) => {
    localStorage.setItem("hrchub_orders", JSON.stringify(orders));
  },

  getHoreca: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_horeca") || "[]");
  },

  saveHoreca: (horeca) => {
    localStorage.setItem("hrchub_horeca", JSON.stringify(horeca));
  },

  getVendors: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_vendors") || "[]");
  },

  saveVendors: (vendors) => {
    localStorage.setItem("hrchub_vendors", JSON.stringify(vendors));
  },

  getRequirements: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_requirements") || "[]");
  },

  saveRequirements: (reqs) => {
    localStorage.setItem("hrchub_requirements", JSON.stringify(reqs));
  },

  getCategories: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_categories") || "[]");
  },

  saveCategories: (cats) => {
    localStorage.setItem("hrchub_categories", JSON.stringify(cats));
  },

  getAdmins: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_admins") || "[]");
  },

  saveAdmins: (admins) => {
    localStorage.setItem("hrchub_admins", JSON.stringify(admins));
  },

  addOrder: (order) => {
    const orders = mockDb.getOrders();
    orders.unshift(order);
    mockDb.saveOrders(orders);
  },

  updateOrderStatus: (id, status, extra = {}) => {
    const orders = mockDb.getOrders();
    const updated = orders.map(o => {
      if (o.id === id) {
        const truckLat = status === "Accepted" ? 10 : status === "Delivered" ? 100 : o.truckLat;
        const temperature = status === "Accepted" ? 4.0 : o.temperature;
        return { ...o, status, truckLat, temperature, ...extra };
      }
      return o;
    });
    mockDb.saveOrders(updated);
  },

  getTickets: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_tickets") || "[]");
  },

  saveTickets: (tickets) => {
    localStorage.setItem("hrchub_tickets", JSON.stringify(tickets));
  },

  getKYC: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_kyc") || "[]");
  },

  saveKYC: (kyc) => {
    localStorage.setItem("hrchub_kyc", JSON.stringify(kyc));
  },

  getFeed: () => {
    mockDb.init();
    return JSON.parse(localStorage.getItem("hrchub_feed") || "[]");
  },

  saveFeed: (feed) => {
    localStorage.setItem("hrchub_feed", JSON.stringify(feed));
  },

  addFeedItem: (item) => {
    const feed = mockDb.getFeed();
    feed.unshift(item);
    mockDb.saveFeed(feed);
  },

  updateFeedItemStatus: (id, status) => {
    const feed = mockDb.getFeed();
    const updated = feed.map(i => i.id === id ? { ...i, status } : i);
    mockDb.saveFeed(updated);
  }
};
